name: mmoChat
version: ${releaseVersion}.${buildNumber}
description: Provides simple chat formatting and channel handling for players.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Chat.MMOChat
depend: [mmoCore]

commands:
    channel:
        description: Turn on or off channels, or set the default channel for speaking
        aliases: [ch, mmochat]
        usage: /channel <name>

permissions:
    mmo.chat:
        description: Access to all the mmoChat channel nodes
        default: false
    mmo.chat.*:
        description: Read/write access to channels
        default: false
    mmo.chat.*.use:
        description: Write access to channels
        default: false
    mmo.chat.*.see:
        description: Read access to channels
        default: false
